const {UNISWAP_FACTORY_ABI, UNISWAP_FACTORY_ADDRESS, UNISWAP_EXCHANGE_ABI }  =  require('./uniswap') 
const {KYBER_RATE_ABI, KYBER_RATE_ADDRESS }  =  require('./kyber') 

module.exports =  {
    UNISWAP_FACTORY_ABI,
    UNISWAP_FACTORY_ADDRESS,
    UNISWAP_EXCHANGE_ABI,

    KYBER_RATE_ABI,
    KYBER_RATE_ADDRESS
}